### ISSUE TITLE
The blog post link 404s

### ISSUE THREAD

**Issue by natesholland** [kabisa/jenkins-docker#7]
The link to the blog post in the README 404s. I want to read the article :cry: Please fix the link so I can read the article :+1:

**Comment by seamyd** [comment]
Hi @natesholland,
thanks for the message. We moved all our (kind off) technical blogs to http://theguild.nl.
I updated the link. Enjoy the article!

**Comment by pascalw** [comment]
@natesholland I am interested in why you got a 404. The old url (http://kabisa.nl/jenkins-docker-awesome-ci/) should redirect to the new url (http://www.theguild.nl/jenkins-docker-awesome-ci). Doesn't that work for you?

**Comment by natesholland** [comment]
It works for me now, I don't know what was up with it last night but it was giving me a 404 page from apache. Thanks for fixing this!
